apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-get-service
  labels:
    app: client-get-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-get-service
  template:
    metadata:
      labels:
        app: client-get-service
    spec:
      containers:
        - name: client-get-service
          image: deamal/client-get-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_HOST
              value: shop-database
---
apiVersion: v1
kind: Service
metadata:
  name: client-get-service
spec:
  selector:
    app: client-get-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080